// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef _FLIGHT_RADAR_UI_H
#define _FLIGHT_RADAR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen2.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_flight_png);    // assets/Flight.png
LV_IMG_DECLARE(ui_img_refresh_24_png);    // assets/refresh_24.png
LV_IMG_DECLARE(ui_img_edit_24_png);    // assets/edit_24.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
