// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_CardBG[1] = {0x0A1024};
const ui_theme_variable_t _ui_theme_alpha_CardBG[1] = {255};

const ui_theme_variable_t _ui_theme_color_CardAircraft[1] = {0x47B805};
const ui_theme_variable_t _ui_theme_alpha_CardAircraft[1] = {255};

const ui_theme_variable_t _ui_theme_color_Gray[1] = {0xA8A8A8};
const ui_theme_variable_t _ui_theme_alpha_Gray[1] = {255};

const ui_theme_variable_t _ui_theme_color_CardRefresh[1] = {0x4E4FE0};
const ui_theme_variable_t _ui_theme_alpha_CardRefresh[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

