// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "../ui.h"

lv_obj_t * uic_splash;
lv_obj_t * uic_wifiPassword;
lv_obj_t * uic_wifiStatus;
lv_obj_t * uic_wifiName;
lv_obj_t * uic_ButtonConnect;
lv_obj_t * uic_step1;
lv_obj_t * uic_ContainerSSIDs;
lv_obj_t * uic_WifiHeader;
lv_obj_t * uic_Panel3;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_WifiHeader = NULL;
lv_obj_t * ui_ContainerSSIDs = NULL;
lv_obj_t * ui_step1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ButtonConnect = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_wifiName = NULL;
lv_obj_t * ui_step2 = NULL;
lv_obj_t * ui_wifiStatus = NULL;
lv_obj_t * ui_wifiPassword = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_splash = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_ButtonConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifi_connect_btn_cb(e);
    }
}

void ui_event_wifiPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_state_modify(ui_Keyboard2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x333540), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel3, lv_pct(47));
    lv_obj_set_height(ui_Panel3, lv_pct(95));
    lv_obj_set_x(ui_Panel3, 16);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_LEFT_MID);

    ui_WifiHeader = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_WifiHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiHeader, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WifiHeader, "Select Wi-Fi network");

    ui_ContainerSSIDs = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_ContainerSSIDs);
    lv_obj_set_width(ui_ContainerSSIDs, lv_pct(100));
    lv_obj_set_height(ui_ContainerSSIDs, lv_pct(90));
    lv_obj_set_x(ui_ContainerSSIDs, 0);
    lv_obj_set_y(ui_ContainerSSIDs, 10);
    lv_obj_set_align(ui_ContainerSSIDs, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerSSIDs, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerSSIDs, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSSIDs, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerSSIDs, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerSSIDs, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_step1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_step1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_step1, 0);
    lv_obj_set_y(ui_step1, -5);
    lv_label_set_text(ui_step1, "1.");
    lv_obj_set_style_text_font(ui_step1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, lv_pct(47));
    lv_obj_set_height(ui_Panel1, lv_pct(95));
    lv_obj_set_x(ui_Panel1, -16);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonConnect = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_ButtonConnect, 100);
    lv_obj_set_height(ui_ButtonConnect, 50);
    lv_obj_set_x(ui_ButtonConnect, 0);
    lv_obj_set_y(ui_ButtonConnect, 150);
    lv_obj_set_align(ui_ButtonConnect, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonConnect);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Connect");

    ui_Label4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "Enter password for");

    ui_wifiName = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_wifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiName, 0);
    lv_obj_set_y(ui_wifiName, 25);
    lv_obj_set_align(ui_wifiName, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_wifiName, "Wifi");

    ui_step2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_step2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_step2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_step2, 0);
    lv_obj_set_y(ui_step2, -5);
    lv_label_set_text(ui_step2, "2.");
    lv_obj_set_style_text_font(ui_step2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatus = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStatus, 0);
    lv_obj_set_y(ui_wifiStatus, 210);
    lv_obj_set_align(ui_wifiStatus, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_wifiStatus, "No WiFi Selected");

    ui_wifiPassword = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_wifiPassword, 280);
    lv_obj_set_height(ui_wifiPassword, 70);
    lv_obj_set_x(ui_wifiPassword, 197);
    lv_obj_set_y(ui_wifiPassword, 100);
    lv_obj_set_align(ui_wifiPassword, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_wifiPassword, "Password");
    lv_textarea_set_password_mode(ui_wifiPassword, true);
    lv_obj_set_style_border_color(ui_wifiPassword, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen2);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_Keyboard2, 715);
    lv_obj_set_height(ui_Keyboard2, 231);
    lv_obj_set_x(ui_Keyboard2, -3);
    lv_obj_set_y(ui_Keyboard2, 108);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_splash = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_splash, lv_pct(100));
    lv_obj_set_height(ui_splash, lv_pct(100));
    lv_obj_set_align(ui_splash, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splash, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_splash);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Flight Radar");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonConnect, ui_event_ButtonConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiPassword, ui_event_wifiPassword, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_wifiPassword);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    uic_Panel3 = ui_Panel3;
    uic_WifiHeader = ui_WifiHeader;
    uic_ContainerSSIDs = ui_ContainerSSIDs;
    uic_step1 = ui_step1;
    uic_ButtonConnect = ui_ButtonConnect;
    uic_wifiName = ui_wifiName;
    uic_wifiStatus = ui_wifiStatus;
    uic_wifiPassword = ui_wifiPassword;
    uic_splash = ui_splash;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    uic_Panel3 = NULL;
    ui_Panel3 = NULL;
    uic_WifiHeader = NULL;
    ui_WifiHeader = NULL;
    uic_ContainerSSIDs = NULL;
    ui_ContainerSSIDs = NULL;
    uic_step1 = NULL;
    ui_step1 = NULL;
    ui_Panel1 = NULL;
    uic_ButtonConnect = NULL;
    ui_ButtonConnect = NULL;
    ui_Label6 = NULL;
    ui_Label4 = NULL;
    uic_wifiName = NULL;
    ui_wifiName = NULL;
    ui_step2 = NULL;
    uic_wifiStatus = NULL;
    ui_wifiStatus = NULL;
    uic_wifiPassword = NULL;
    ui_wifiPassword = NULL;
    ui_Keyboard2 = NULL;
    uic_splash = NULL;
    ui_splash = NULL;
    ui_Label8 = NULL;

}
