// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_WifiHeader;
extern lv_obj_t * ui_ContainerSSIDs;
extern lv_obj_t * ui_step1;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ButtonConnect(lv_event_t * e);
extern lv_obj_t * ui_ButtonConnect;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_wifiName;
extern lv_obj_t * ui_step2;
extern lv_obj_t * ui_wifiStatus;
extern void ui_event_wifiPassword(lv_event_t * e);
extern lv_obj_t * ui_wifiPassword;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_splash;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Panel3;
extern lv_obj_t * uic_WifiHeader;
extern lv_obj_t * uic_ContainerSSIDs;
extern lv_obj_t * uic_step1;
extern lv_obj_t * uic_ButtonConnect;
extern lv_obj_t * uic_wifiName;
extern lv_obj_t * uic_wifiStatus;
extern lv_obj_t * uic_wifiPassword;
extern lv_obj_t * uic_splash;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

